// <auto-generated />
using LocalBiz.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBiz.Migrations
{
    [DbContext(typeof(LocalBizContext))]
    [Migration("20200821194114_Secondary")]
    partial class Secondary
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBiz.Models.Biz", b =>
                {
                    b.Property<int>("BizId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.Property<string>("Url");

                    b.HasKey("BizId");

                    b.ToTable("Bizs");

                    b.HasData(
                        new
                        {
                            BizId = 1,
                            Address = "#1 Happy Street, Chicago, IL",
                            Name = "Wok With Me",
                            Type = "Restaurant - Chinese",
                            Url = "info@wokwithme.com"
                        },
                        new
                        {
                            BizId = 2,
                            Address = "405 - 3 Wacker Drive, Chicago, IL",
                            Name = "Great Lakes Bank",
                            Type = "Financial - Bank",
                            Url = "info@glbanking.com"
                        },
                        new
                        {
                            BizId = 3,
                            Address = "#455 Michigan Avenue, Chicago, IL",
                            Name = "Panera",
                            Type = "Restaurant - American",
                            Url = "info@panera.com"
                        },
                        new
                        {
                            BizId = 4,
                            Address = "#4334 Williams Street, Chicago, IL",
                            Name = "Tip Top Tailor",
                            Type = "Dry Cleaning/Tailor",
                            Url = "charlie@tiptop.com"
                        },
                        new
                        {
                            BizId = 5,
                            Address = "#253 Jackson Avenue, Chicago, IL",
                            Name = "Euro Cars",
                            Type = "Auto Mechanic",
                            Url = "info@eurocars.com"
                        },
                        new
                        {
                            BizId = 6,
                            Address = "#3446 - 55 N. Wacker Drive, Chicago, IL",
                            Name = "Pretzel Choke",
                            Type = "Restaurant - German",
                            Url = "info@pretzelchoke.com"
                        },
                        new
                        {
                            BizId = 7,
                            Address = "#478 Cander Avenue, Chicago, IL",
                            Name = "Trip and Slide",
                            Type = "Recreational - Roller Rink",
                            Url = "info@tripandslide.com"
                        },
                        new
                        {
                            BizId = 8,
                            Address = "#3 Anderson Road, Chicago, IL",
                            Name = "Green Tongue",
                            Type = "Restaurant - Health Food",
                            Url = "info@greentongue.com"
                        },
                        new
                        {
                            BizId = 9,
                            Address = "#4446 - 305 Jackson Avenue, Chicago, IL",
                            Name = "Tax Grind",
                            Type = "Financial - Tax Preparation",
                            Url = "info@taxgrind.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
